import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

sns.set_theme(style="whitegrid", palette="muted")

df = pd.read_csv('seasonal_agriculture_performance_dataset.csv')

# Insights Generation
seasonal_metrics = df.groupby('Season')[['Yield_Tonnes_Ha', 'Profit_INR', 'Revenue_INR', 'Water_Used_m3']].mean().reset_index()
best_yield_season = seasonal_metrics.loc[seasonal_metrics['Yield_Tonnes_Ha'].idxmax()]['Season']
best_profit_season = seasonal_metrics.loc[seasonal_metrics['Profit_INR'].idxmax()]['Season']

md_content = f"""# Presentation Content: Seasonal Agriculture Performance Analysis

Here is the suggested content to fill in your `VOIS_Major_Project_PPT_Submission_Template.pptx`.

## Slide 1: Title Slide
- **Title**: Seasonal Agriculture Performance Analysis
- **Subtitle**: Identifying Patterns, Trends, and Differences Across Seasons
- **Presenter**: [Your Name] / [Your Team]
- **Date**: 10 September 2026

## Slide 2: Objective & Problem Statement
- **Objective**: To analyze agricultural data from different seasons and identify meaningful patterns, trends, relationships and differences in agricultural performance.
- **Problem Statement**: Agricultural activities are influenced by seasonal variations. This project investigates how raw agricultural data changes across seasons (Kharif, Rabi, etc.) to understand differences in resource usage, environmental impact, and economic outcomes.

## Slide 3: Dataset Overview
- **Dataset Size**: {df.shape[0]} records and {df.shape[1]} features.
- **Key Features Analyzed**: Crop, Season, Yield (Tonnes/Ha), Profit (INR), Water Used (m³), and Environmental Factors (Rainfall, Temperature).
- **Data Quality**: The dataset was cleaned and verified for missing or inconsistent values before analysis.

## Slide 4: Seasonal Variations in Yield
- **Insight**: Yield varies significantly depending on the season.
- **Key Finding**: The **{best_yield_season}** season demonstrated the highest average yield per hectare compared to other seasons.
- **Visual suggestion**: Insert the `yield_by_season.png` chart generated by the Jupyter Notebook here.

## Slide 5: Economic Outcomes (Profitability)
- **Insight**: High yield does not always guarantee the highest profit due to varying costs and market prices.
- **Key Finding**: The most profitable season on average was **{best_profit_season}**.
- **Visual suggestion**: Insert the `profit_by_season.png` boxplot here.

## Slide 6: Resource Usage (Water Efficiency)
- **Insight**: Water usage and efficiency fluctuate across seasons due to changing rainfall and temperatures.
- **Key Finding**: Some seasons rely heavily on irrigation, leading to lower overall water efficiency (Tonnes per 1000m³).
- **Visual suggestion**: Insert the `resource_usage.png` chart here.

## Slide 7: Environmental Factors Impact
- **Insight**: Rainfall and Soil Moisture have strong positive correlations with crop yield.
- **Key Finding**: Adequate sunlight hours and optimal temperature ranges directly influence the final agricultural output.
- **Visual suggestion**: Insert the `correlation_heatmap.png` chart here.

## Slide 8: Recommendations & Conclusion
- **Recommendation 1**: Optimize water usage during dry seasons by adopting more efficient irrigation methods (e.g., Drip Irrigation) to maintain profitability.
- **Recommendation 2**: Align crop selection with expected seasonal rainfall to maximize yield naturally and reduce dependency on artificial resources.
- **Conclusion**: Seasonal variations play a critical role in agricultural performance. By strategically planning resource allocation according to the season, farmers can significantly improve both their yield and economic return.

---
**Note**: Please run all the cells in your `Seasonal_Agriculture_Analysis.ipynb` to generate the `.png` image files needed for the slides!
"""

with open('PPT_Insights_and_Content.md', 'w', encoding='utf-8') as f:
    f.write(md_content)

print("PPT Insights generated successfully.")
